-- select * from "SelectOptions"
insert into "SelectOptions" ("ID", "PropertyID", "Name", "MetaDate", "NameMultiLangJson")
values 
(1 ,1 ,'вишня' ,'{"background-color": "#880E4F", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"вишня"},{"LangName":"kk","Value":"шие"},{"LangName":"en","Value":"cherry"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(2 ,1 ,'хамелеон' ,'{"background": "linear-gradient(-25deg, #FD2323, #00FFD0)", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"хамелеон"},{"LangName":"kk","Value":"хамелеон"},{"LangName":"en","Value":"chameleon"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(3 ,1 ,'бежевый' ,'{"background-color": "#F0DEBA", "color":"black"}' ,'[{"LangName":"ru-RU","Value":"бежевый"},{"LangName":"kk","Value":"сорғылт қоңыр"},{"LangName":"en","Value":"beige"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(4 ,1 ,'белый' ,'{"background-color":"#FFF", "color":"black"}' ,'[{"LangName":"ru-RU","Value":"белый"},{"LangName":"kk","Value":"сорғылт қоңыр"},{"LangName":"en","Value":"beige"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(5 ,1 ,'бирюзовый' ,'{"background-color":"#70B6B3", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"бирюзовый"},{"LangName":"kk","Value":"көгілдір"},{"LangName":"en","Value":"turquoise"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(6 ,1 ,'бордовый' ,'{"background-color":"#3E2723", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"бордовый"},{"LangName":"kk","Value":"күрең"},{"LangName":"en","Value":"vinous"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(7 ,1 ,'голубой' ,'{"background-color":"#00838F", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"голубой"},{"LangName":"kk","Value":"көк"},{"LangName":"en","Value":"blue"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(8 ,1 ,'желтый' ,'{"background-color":"#F8EF85", "color":"black"}' ,'[{"LangName":"ru-RU","Value":"желтый"},{"LangName":"kk","Value":"сары"},{"LangName":"en","Value":"yellow"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(9 ,1 ,'зеленый' ,'{"background-color":"#33691E", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"зеленый"},{"LangName":"kk","Value":"жасыл"},{"LangName":"en","Value":"green"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(10 ,1 ,'золотистый' ,'{"background-color":"gold", "color":"black"}' ,'[{"LangName":"ru-RU","Value":"золотистый"},{"LangName":"kk","Value":"алтын"},{"LangName":"en","Value":"golden"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(11 ,1 ,'коричневый' ,'{"background-color":"brown", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"коричневый"},{"LangName":"kk","Value":"қоңыр"},{"LangName":"en","Value":"brown"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(12 ,1 ,'красный' ,'{"background-color":"#B71C1C", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"красный"},{"LangName":"kk","Value":"қызыл"},{"LangName":"en","Value":"red"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(13 ,1 ,'оранжевый' ,'{"background-color":"orange", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"оранжевый"},{"LangName":"kk","Value":"апельсин"},{"LangName":"en","Value":"Orange"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(14 ,1 ,'розовый' ,'{"background-color":"#F218AF", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"розовый"},{"LangName":"kk","Value":"қызғылт"},{"LangName":"en","Value":"pink"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(15 ,1 ,'серебристый' ,'{"background-color":"silver", "color":"black"}' ,'[{"LangName":"ru-RU","Value":"серебристый"},{"LangName":"kk","Value":"күміс"},{"LangName":"en","Value":"silver"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(16 ,1 ,'серый' ,'{"background-color":"#424242", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"серый"},{"LangName":"kk","Value":"сұр"},{"LangName":"en","Value":"gray"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(17 ,1 ,'синий' ,'{"background-color":"#0D47A1", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"синий"},{"LangName":"kk","Value":"көк"},{"LangName":"en","Value":"blue"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(18 ,1 ,'сиренивый' ,'{"background-color":"#CC99FF", "color":"black"}' ,'[{"LangName":"ru-RU","Value":"сиренивый"},{"LangName":"kk","Value":"жұпаргүл"},{"LangName":"en","Value":"lilac"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(19 ,1 ,'фиолетовый' ,'{"background-color":"#860F89", "color":"white"}' ,'[{"LangName":"ru-RU","Value":"фиолетовый"},{"LangName":"kk","Value":"күлгін"},{"LangName":"en","Value":"purple"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(20 ,1 ,'черный' ,'{"background-color":"black"}' ,'[{"LangName":"ru-RU","Value":"черный"},{"LangName":"kk","Value":"қара"},{"LangName":"en","Value":"black"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(21 ,2 ,'седан' ,null ,null),
(22 ,2 ,'универсал' ,null ,null),
(23 ,2 ,'хэтчбек/лифтбек' ,null ,null),
(24 ,2 ,'лимузин' ,null ,null),
(25 ,2 ,'купе' ,null ,null),
(26 ,2 ,'кабриолет' ,null ,null),
(27 ,2 ,'внедорожник' ,null ,null),
(28 ,3 ,'бензин' ,null ,null),
(29 ,3 ,'дизель' ,null ,null),
(30 ,3 ,'газ-бензин' ,null ,null),
(31 ,3 ,'газ' ,null ,null),
(32 ,3 ,'гибрид' ,null ,null),
(33 ,3 ,'электричество' ,null ,null),
(34 ,5 ,'gasoline' ,null ,'[{"LangName":"ru-RU","Value":"Бензин"},{"LangName":"kk","Value":"бензин"},{"LangName":"en","Value":"gasoline"},{"LangName":"de","Value":"gasoline"},{"LangName":"he","Value":"בנזין"}]'),
(35 ,5 ,'diesel' ,null ,'[{"LangName":"ru-RU","Value":"Бизель"},{"LangName":"kk","Value":"Бизель"},{"LangName":"en","Value":"diesel"},{"LangName":"de","Value":"diesel"},{"LangName":"he","Value":"דיזל"}]'),
(36 ,5 ,'gas' ,null ,'[{"LangName":"ru-RU","Value":"газ"},{"LangName":"kk","Value":"газ"},{"LangName":"en","Value":"gas"},{"LangName":"de","Value":"gas"},{"LangName":"he","Value":"גז"}]'),
(37 ,5 ,'gasPetrol' ,null ,'[{"LangName":"ru-RU","Value":"газ-бензин"},{"LangName":"kk","Value":"газ-жағар май құю"},{"LangName":"en","Value":"gas-petrol"},{"LangName":"de","Value":"Gas-Benzin"},{"LangName":"he","Value":"גז ודלק"}]'),
(38 ,5 ,'hybrid' ,null ,'[{"LangName":"ru-RU","Value":"Гибрид"},{"LangName":"kk","Value":"гибридті"},{"LangName":"en","Value":"hybrid"},{"LangName":"de","Value":"Hybrid"},{"LangName":"he","Value":"היברידי"}]'),
(39 ,5 ,'electricity' ,null ,'[{"LangName":"ru-RU","Value":"электричество"},{"LangName":"kk","Value":"электр"},{"LangName":"en","Value":"electricity"},{"LangName":"de","Value":"Strom"},{"LangName":"he","Value":"חשמל"}]'),
(40 ,10 ,'DoubleCycles' ,null ,'[{"LangName":"ru-RU","Value":"2-тактный"},{"LangName":"kk","Value":"2-инсульт"},{"LangName":"en","Value":"2-stroke"},{"LangName":"de","Value":"2-Takt"},{"LangName":"he","Value":"2 אונליין"}]'),
(41 ,10 ,'4Cycle' ,null ,'[{"LangName":"ru-RU","Value":"4-тактный"},{"LangName":"kk","Value":"4-тактный"},{"LangName":"en","Value":"4-stroke"},{"LangName":"de","Value":"4-Takt"},{"LangName":"he","Value":"4 פעימות"}]'),
(42 ,11 ,'40cm' ,null ,'[{"LangName":"ru-RU","Value":"40-см"},{"LangName":"kk","Value":"40-см"},{"LangName":"en","Value":"40-см"},{"LangName":"de","Value":"40-см"},{"LangName":"he","Value":"40 ס\"מ"}]'),
(43 ,11 ,'50cm' ,null ,'[{"LangName":"ru-RU","Value":"50-см"},{"LangName":"kk","Value":"50-см"},{"LangName":"en","Value":"50-cm"},{"LangName":"de","Value":"50-cm"},{"LangName":"he","Value":"50-cm"}]'),
(44 ,11 ,'60cm' ,null ,'[{"LangName":"ru-RU","Value":"60-см"},{"LangName":"kk","Value":"60-см"},{"LangName":"en","Value":"60-cm"},{"LangName":"de","Value":"60-cm"},{"LangName":"he","Value":"60-cm"}]'),
(45 ,27 ,'air' ,null ,'[{"LangName":"ru-RU","Value":"Воздух"},{"LangName":"kk","Value":"салқындату"},{"LangName":"en","Value":"Cooling"},{"LangName":"de","Value":"Kühlung"},{"LangName":"he","Value":"קירור"}]'),
(46 ,28 ,'belt' ,null ,'[{"LangName":"ru-RU","Value":"ремень"},{"LangName":"kk","Value":"белдік"},{"LangName":"en","Value":"belt"},{"LangName":"de","Value":"Gürtel"},{"LangName":"he","Value":"חגורה"}]'),
(47 ,27 ,'AirOil' ,null ,'[{"LangName":"ru-RU","Value":"воздушно-масляное"},{"LangName":"kk","Value":"әуе-мұнай"},{"LangName":"en","Value":"air-oil"},{"LangName":"de","Value":"Luft-Öl"},{"LangName":"he","Value":"אוויר-שמן"}]'),
(48 ,28 ,'cardan' ,null ,'[{"LangName":"ru-RU","Value":"кардан"},{"LangName":"kk","Value":"кардан"},{"LangName":"en","Value":"cardan"},{"LangName":"de","Value":"Gelenkkupplung"},{"LangName":"he","Value":"קרדן"}]'),
(49 ,27 ,'liquid' ,null ,'[{"LangName":"ru-RU","Value":"жидкостное"},{"LangName":"kk","Value":"сұйық"},{"LangName":"en","Value":"liquid"},{"LangName":"de","Value":"Flüssigkeit"},{"LangName":"he","Value":"נוזל"}]'),
(50 ,28 ,'chain' ,null ,'[{"LangName":"ru-RU","Value":"цепь"},{"LangName":"kk","Value":"шынжыр"},{"LangName":"en","Value":"chain"},{"LangName":"de","Value":"Kette"},{"LangName":"he","Value":"שרשרת"}]'),
(51 ,29 ,'Mechanics' ,null ,'[{"LangName":"ru-RU","Value":"механика"},{"LangName":"kk","Value":"механика"},{"LangName":"en","Value":"Mechanics"},{"LangName":"de","Value":"Mechanik"},{"LangName":"he","Value":"מכניקה"}]'),
(52 ,29 ,'AutomaticTransmission' ,null ,'[{"LangName":"ru-RU","Value":"АКПП"},{"LangName":"kk","Value":"АКПП"},{"LangName":"en","Value":"automatic transmission"},{"LangName":"de","Value":"Automatikgetriebe"},{"LangName":"he","Value":"תיבת הילוכים אוטומטית"}]'),
(53 ,29 ,'robotic' ,null ,'[{"LangName":"ru-RU","Value":"роботизированная"},{"LangName":"kk","Value":""},{"LangName":"en","Value":"robotic"},{"LangName":"de","Value":""},{"LangName":"he","Value":""}]'),
(54 ,9 ,'1' ,null ,'[{"LangName":"ru-RU","Value":"1-ц"},{"LangName":"kk","Value":"1-ц"},{"LangName":"en","Value":"1-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(55 ,9 ,'2' ,null ,'[{"LangName":"ru-RU","Value":"2-ц"},{"LangName":"kk","Value":"2-ц"},{"LangName":"en","Value":"2-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(56 ,9 ,'3' ,null ,'[{"LangName":"ru-RU","Value":"3-ц"},{"LangName":"kk","Value":"3-ц"},{"LangName":"en","Value":"3-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(57 ,9 ,'4' ,null ,'[{"LangName":"ru-RU","Value":"4-ц"},{"LangName":"kk","Value":"4-ц"},{"LangName":"en","Value":"4-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(58 ,9 ,'5' ,null ,'[{"LangName":"ru-RU","Value":"5-ц"},{"LangName":"kk","Value":"5-ц"},{"LangName":"en","Value":"5-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(59 ,9 ,'6' ,null ,'[{"LangName":"ru-RU","Value":"6-ц"},{"LangName":"kk","Value":"6-ц"},{"LangName":"en","Value":"6-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(60 ,9 ,'8' ,null ,'[{"LangName":"ru-RU","Value":"8-ц"},{"LangName":"kk","Value":"8-ц"},{"LangName":"en","Value":"8-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(61 ,9 ,'10' ,null ,'[{"LangName":"ru-RU","Value":"10-ц"},{"LangName":"kk","Value":"10-ц"},{"LangName":"en","Value":"10-c"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]')
ON CONFLICT ("ID") DO UPDATE SET
"MetaDate" = excluded."MetaDate";


-------------------------------------------------------------------------------------------------------------