insert into "Categories" ("ID", "Name", "Alias", "FileName", "NameMultiLangJson", 
						  "NameMultiLangSingularJson", "SuperCategID", "CategGroupID", "Status", "HideModelField")
values 
(1 ,'Мопеды и скутеры','Mopedy-i-skutery' ,'skooter_small.webp' ,'[{"LangName":"ru-RU","Value":"Мопеды и скутеры"},{"LangName":"kk","Value":"Мопедтер және скутерлер"},{"LangName":"en","Value":"Mopeds and scooters"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',null,1 ,1 ,1 ,'0'),
(2 ,'Мотоциклы','Motocikly' ,'Moto_small.webp' ,'[{"LangName":"ru-RU","Value":"Мотоциклы"},{"LangName":"kk","Value":"Мотоциклдер"},{"LangName":"en","Value":"Motorcycles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]','[{"LangName":"ru-RU","Value":"Мотоцикл"},{"LangName":"kk","Value":"Мотоцикл"},{"LangName":"en","Value":"Motorcycles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',1 ,1 ,1 ,'0'),
(3 ,'Квадроциклы','Kvadrocikly' ,'qmoto_small.webp' ,'[{"LangName":"ru-RU","Value":"Квадроциклы"},{"LangName":"kk","Value":"Квадроциклдер"},{"LangName":"en","Value":"Quad bikes"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]','[{"LangName":"ru-RU","Value":"Квадроцикл"},{"LangName":"kk","Value":"Квадроцикл"},{"LangName":"en","Value":"Quad bikes"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',1 ,1 ,1 ,'0'),
(4 ,'Снегоходы','Snegohody' ,'msnow.webp' ,'[{"LangName":"ru-RU","Value":"Снегоходы"},{"LangName":"kk","Value":"Қарда жүргіштер"},{"LangName":"en","Value":"Snowmobiles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]','[{"LangName":"ru-RU","Value":"Снегоход"},{"LangName":"kk","Value":"Қарда жүргіш"},{"LangName":"en","Value":"Snowmobiles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',1 ,1 ,1 ,'0'),
(5 ,'Вездеходы','Vezdekhody' ,'all_road_small.webp' ,'[{"LangName":"ru-RU","Value":"Вездеходы"},{"LangName":"kk","Value":"Кез-келген жерден жүре беретіндер"},{"LangName":"en","Value":"All-terrain vehicles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]','[{"LangName":"ru-RU","Value":"Вездеход"},{"LangName":"kk","Value":"Кез-келген жерден жүре беретін"},{"LangName":"en","Value":"All-terrain vehicles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',1 ,1 ,1 ,'0'),
(6 ,'Автодома','Avtodoma' ,'moto_house_small.webp' ,'[{"LangName":"ru-RU","Value":"Автодома"},{"LangName":"kk","Value":"Автодома"},{"LangName":"en","Value":"Recreational vehicles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]','[{"LangName":"ru-RU","Value":"Автодом"},{"LangName":"kk","Value":"Автодом"},{"LangName":"en","Value":"Recreational vehicles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',1 ,1 ,1 ,'0'),
(7 ,'Велосипеды','Velosipedy' ,'bicycle_small.webp' ,'[{"LangName":"ru-RU","Value":"Велосипеды"},{"LangName":"kk","Value":"Велосипедтер"},{"LangName":"en","Value":"Bicycles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]','[{"LangName":"ru-RU","Value":"Велосипеды"},{"LangName":"kk","Value":"Велосипедтер"},{"LangName":"en","Value":"Bicycles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',1 ,1 ,1 ,'0'),
(8 ,'Прицепы','Pricepy' ,'pr.webp' ,'[{"LangName":"ru-RU","Value":"Прицепы"},{"LangName":"kk","Value":"Тіркемелер"},{"LangName":"en","Value":"Trailers"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',null,1 ,1 ,1 ,'0'),
(9 ,'Катера и яхты','Katera-i-yahty' ,'yaht_small.webp' ,'[{"LangName":"ru-RU","Value":"Катера и яхты"},{"LangName":"kk","Value":"Катерлер және яхталар"},{"LangName":"en","Value":"Motor boats and yachts"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',null,2 ,1 ,1 ,'0'),
(10 ,'Гидроциклы','Gidrocikly' ,'waterbike.webp' ,'[{"LangName":"ru-RU","Value":"Гидроциклы"},{"LangName":"kk","Value":"Гидроциклдер"},{"LangName":"en","Value":"Hydrocycles"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',null,2 ,1 ,1 ,'0'),
(11 ,'Лодки','Lodki' ,'mboat_small.webp' ,'[{"LangName":"ru-RU","Value":"Лодки"},{"LangName":"kk","Value":"Қайықтар"},{"LangName":"en","Value":"Boats"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',null,2 ,1 ,1 ,'0'),
(12 ,'подвесные лодочные моторы','podvesnye-lodochnye-motory' ,'boat_engine.webp' ,'[{"LangName":"ru-RU","Value":"Лодочные моторы"},{"LangName":"kk","Value":"Қайық моторы"},{"LangName":"en","Value":"Boat motors"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',null,2 ,1 ,1 ,'0'),
(13 ,'Автозвук','Avtozvuk' ,null ,null,null,5 ,1 ,0 ,'0'),
(14 ,'Автомойки','Avtomojki' ,null ,null,null,5 ,1 ,0 ,'0'),
(15 ,'Автострахование','Avtostraxovanie' ,null ,null,null,5 ,1 ,0 ,'0'),
(16 ,'Автошколы','Avtoshkoly' ,null ,null,null,5 ,1 ,0 ,'0'),
(17 ,'Автоэлектрики','Avtoelektriki' ,null ,null,null,5 ,1 ,0 ,'0'),
(18 ,'Аэрография','Aerografiya' ,null ,null,null,5 ,1 ,0 ,'0'),
(19 ,'Вскрытие авто, изготовление ключей','Vskrytie-avto-izgotovlenie-klyuchej' ,null ,null,null,5 ,1 ,0 ,'0'),
(20 ,'Грузоперевозки','Gruzoperevozki' ,null ,null,null,5 ,1 ,0 ,'0'),
(21 ,'Замена масел, жидкостей','Zamena-masel-zhidkostej' ,null ,null,null,5 ,1 ,0 ,'0'),
(22 ,'Ксенон','Ksenon' ,null ,null,null,5 ,1 ,0 ,'0'),
(23 ,'Перетяжка салона, пошив чехлов','Peretyazhka-salona-poshiv-chexlov' ,null ,null,null,5 ,1 ,0 ,'0'),
(24 ,'Прокат, аренда','Prokat-arenda' ,null ,null,null,5 ,1 ,0 ,'0'),
(25 ,'Ремонт бамперов, автопластика','Remont-bamperov-avtoplastika' ,null ,null,null,5 ,1 ,0 ,'0'),
(26 ,'Ремонт двигателя','Remont-dvigatelya' ,null ,null,null,5 ,1 ,0 ,'0'),
(27 ,'Ремонт КПП','Remont-KPP' ,null ,null,null,5 ,1 ,0 ,'0'),
(28 ,'Ремонт кузова','Remont-kuzova' ,null ,null,null,5 ,1 ,0 ,'0'),
(29 ,'Ремонт радиаторов, кондиционеров','Remont-radiatorov-kondicionerov' ,null ,null,null,5 ,1 ,0 ,'0'),
(30 ,'Ремонт ходовой','Remont-xodovoj' ,null ,null,null,5 ,1 ,0 ,'0'),
(31 ,'Ремонт топливной системы','Remont-toplivnoj-sistemy' ,null ,null,null,5 ,1 ,0 ,'0'),
(32 ,'Сигнализации','Signalizacii' ,null ,null,null,5 ,1 ,0 ,'0'),
(33 ,'СТО, автосервисы','STO-avtoservisy' ,null ,null,null,5 ,1 ,0 ,'0'),
(34 ,'Такси','Taksi' ,null ,null,null,5 ,1 ,0 ,'0'),
(35 ,'Тех. осмотр','Tex-osmotr' ,null ,null,null,5 ,1 ,0 ,'0'),
(36 ,'Тонировка','Tonirovka' ,null ,null,null,5 ,1 ,0 ,'0'),
(37 ,'легковые автомобили','legkovye-avtomobili' ,'car_small.webp' ,'[{"LangName":"ru-RU","Value":"легковые автомобили"},{"LangName":"kk","Value":"легковые автомобили"},{"LangName":"en","Value":"personal cars"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]',null,7 ,1 ,1 ,'0');

-------------------------------------------------------------------------------------------------------------


