insert into "Type" ("ID", "Name", "Comment", "Status", "WatchWeightStatus", "NameMultiLangJson")
values
(1 ,'кросс и эндуро' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"кросс и эндуро"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(2 ,'горный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"горный"},{"LangName":"en","Value":"mokik"},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(3 ,'детский' ,null ,1 ,1 ,'[{"LangName":"ru-ru","Value":"детский"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(4 ,'туринговый' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"туринговый"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(5 ,'утилитарный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"утилитарный"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(6 ,'дорожный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"дорожный"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(7 ,'чоппер' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"чоппер"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(8 ,'кастом-байк' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"кастом-байк"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(9 ,'спортивный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"спортивный"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(10 ,'трайк' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"трайк"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(11 ,'мопед' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"мопед"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(12 ,'скутер' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"скутер"},{"LangName":"en","Value":"skooter"},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(13 ,'мотовездеход' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"мотовездеход"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(14 ,'багги' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"багги"},{"LangName":"en","Value":"bagy"},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(15 ,'вездеход' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"вездеход"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(16 ,'амфибия' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"амфибия"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(17 ,'BMX' ,null ,1 ,2 ,null),
(18 ,'для семейного отдыха' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"для семейного отдыха"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(19 ,'моторная' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"моторная"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(20 ,'вёсельная' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"вёсельная"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(21 ,'подвесной' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"подвесной"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(22 ,'стационарный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"стационарный"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(23 ,'альковный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"альковный"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(24 ,'жилой модуль' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"жилой модуль"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(25 ,'интегрированный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"интегрированный"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(26 ,'полуинтегрированный' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"полуинтегрированный"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(27 ,'кастенваген' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"кастенваген"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(28 ,'катер' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"катер"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(29 ,'моторная яхта' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"моторная яхта"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(30 ,'парусная яхта' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"парусная яхта"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(31 ,'шлемы' ,'Экипировка' ,1 ,2 ,'[{"LangName":"ru-ru","Value":"шлемы"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(32 ,'защита' ,'Экипировка' ,1 ,2 ,'[{"LangName":"ru-ru","Value":"защита"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(33 ,'одежда' ,'Экипировка' ,1 ,2 ,'[{"LangName":"ru-ru","Value":"одежда"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(34 ,'обувь' ,'Экипировка' ,1 ,2 ,'[{"LangName":"ru-ru","Value":"обувь"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(35 ,'перчатки' ,'Экипировка' ,1 ,2 ,'[{"LangName":"ru-ru","Value":"перчатки"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(36 ,'прочее' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"прочее"},{"LangName":"en","Value":"other"},{"LangName":"de","Value":"anderen"},{"LangName":"kk","Value":""}]'),
(37 ,'кроссовер' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"кроссовер"},{"LangName":"en","Value":"crossover"},{"LangName":"de","Value":"crossover"},{"LangName":"kk","Value":""}]'),
(38 ,'туристический' ,null ,1 ,2 ,'[{"LangName":"ru-ru","Value":"туристический"},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"kk","Value":""}]'),
(39 ,'automobile' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Легковые"},{"LangName":"kk","Value":"Легковые"},{"LangName":"en","Value":"automobile"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(40 ,' Minivans and minibuses' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Минивены и микроавтобусы"},{"LangName":"kk","Value":"Минивены и микроавтобусы"},{"LangName":"en","Value":"
Minivans and minibuses"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(41 ,'SUVs and pickups' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Внедорожники и пикапы"},{"LangName":"kk","Value":"Внедорожники и пикапы"},{"LangName":"en","Value":"SUVs and pickups"},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(42 ,'Колеса диаметром 26’' ,'Колеса диаметром 26’ (велосипеды)' ,1 ,0 ,null),
(43 ,'Колеса диаметром 27,5’' ,'Колеса диаметром 27,5’ (велосипеды)' ,1 ,0 ,null),
(44 ,'Колеса диаметром 29’ (найнеры)' ,'Колеса диаметром 29’ (найнеры) (велосипеды)' ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Колеса диаметром 29’ (найнеры)"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(45 ,'Велосипед двухподвес' ,'Велосипед' ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Велосипед двухподвес"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(46 ,'Велосипеды Гибриды' ,'Велосипеды Гибриды / Cross / Touring' ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Велосипеды Гибриды / Cross / Touring"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(47 ,'Женские велосипеды' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Женские велосипеды"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(48 ,'Складные велосипеды' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Складные велосипеды"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(49 ,'Циклокроссовые велосипеды' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Циклокроссовые велосипеды"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(50 ,'Шоссейные велосипеды' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Шоссейные велосипеды"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(51 ,'Электровелосипеды' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Электровелосипеды"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(52 ,'Premium велосипеды' ,null ,1 ,0 ,'[{"LangName":"ru-RU","Value":"Premium велосипеды"},{"LangName":"kk","Value":""},{"LangName":"en","Value":""},{"LangName":"de","Value":""},{"LangName":"he","Value":""},{"LangName":"hy-AM","Value":""}]'),
(53, 'лодочные'	,null,		1 ,0 ,null),
(54, 'платформа',null,		1 ,0 ,null),
(55, 'одноосные',null,		1 ,0 ,null),
(56, 'двухостные',null,		1 ,0 ,null),
(57, 'для квадроцикла',null, 1 ,0 ,null),
(58, 'для снегохода',null,	1 ,0 ,null),
(59, 'для водной техники',null,	1 ,0 ,null),
(60, 'для спецтехники'	,null,	1 ,0 ,null);

-------------------------------------------------------------------------------------------------------------


